language: node_js

node_js:
  - "stable"

after_success:
  - chmod 600 deploy-key
  - mv deploy-key ~/.ssh/id_rsa
  - git remote add deploy ssh://root@104.236.41.203/var/lib/co-code/site.git
  - git push deploy

before_install:
  - openssl aes-256-cbc -K $encrypted_8f0deb3e3681_key -iv $encrypted_8f0deb3e3681_iv
  -in deploy_key.enc -out deploy_key -d
